version: '3.9'

services:
  postgres_db:
    image: postgres:15.5-alpine3.19
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3-alpine3.18
    container_name: redis
    restart: always
    env_file:
      - .env
    volumes:
      - redis_data:/data

  auth_api:
    container_name: AuthAPI
    command: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:9999
    env_file:
      - .env
    environment:
      PYTHONPATH: /src
    volumes:
      - ./src:/src
    build:
      context: src
      dockerfile: Dockerfile
    depends_on:
      postgres_db:
        condition: service_started
      redis:
        condition: service_started

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/auth_api.conf:/etc/nginx/conf.d/auth_api.conf:ro
    depends_on:
      auth_api:
        condition: service_started
    ports:
      - "8080:8080"
volumes:
  pg_data:
  redis_data: