version: '3.9'

services:
  test_db:
    image: postgres:15.5-alpine3.19
    container_name: test_db
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - test_pg_data:/var/lib/postgresql/data

  test_redis:
    image: redis:7.2.3-alpine3.18
    container_name: tets_redis
    restart: always
    env_file:
      - .env
    volumes:
      - test_redis_data:/data

  test_auth_api:
    container_name: test_auth_api
    image:
    command: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:9999
    env_file:
      - .env


  pytest_api:
    container_name: pytest_api
    build:
      context: tests
      dockerfile: dockerfile
    env_file:
      - .env

volumes:
  test_pg_data:
  test_redis_data: