version: '3.9'

services:
  postgres_db:
    image: postgres:15.5-alpine3.19
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3-alpine3.18
    container_name: redis
    restart: always
    env_file:
      - .env
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data: