version: '3.9'

services:
  postgres_db:
    image: postgres:15.5-alpine3.19
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: